services:
  mysql:
    image: mysql:8.4
    container_name: wasm_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: wasm_editor
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - mysql_data:/var/lib/mysql

  php:
    image: webdevops/php-apache:8.3
    container_name: wasm_php
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      - WEB_DOCUMENT_ROOT=/app
      - DB_HOST=mysql

volumes:
  mysql_data:
